#version 450

layout(set = 0, binding = 0, rgba32f) uniform image2D TextureToFill;

layout(set = 0, binding = 1) uniform FillValueBuffer
{
    float FillValue;
    vec3 Padding_;
};

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main()
{
    ivec2 textureCoordinate = ivec2(gl_GlobalInvocationID.xy);
    vec4 dataToStore = vec4(FillValue);
    imageStore(TextureToFill, textureCoordinate, dataToStore);
}
